export type {
  CRMAccount,
  CRMActivity,
  CRMAddress,
  CRMAdapter,
  CRMAdapterCapabilities,
  CRMAdapterFactory,
  CRMAdapterFactoryInput,
  CRMContact,
  CRMCustomField,
  CRMDeal,
  CRMEmail,
  CRMEntityType,
  CRMLead,
  CRMNote,
  CRMOwner,
  CRMPhone,
  CRMPipeline,
  CRMSocialHandle,
  CRMStage,
  CRMSyncDirection,
  CRMTask,
  CRMVendor,
} from "./types";
export {
  createInMemoryCRMTokenStore,
  createPostgresCRMTokenStore,
  createRedisCRMTokenStore,
  createSqliteCRMTokenStore,
} from "./stores";
export type {
  CreateInMemoryCRMTokenStoreOptions,
  CreatePostgresCRMTokenStoreOptions,
  CreateRedisCRMTokenStoreOptions,
  CreateSqliteCRMTokenStoreOptions,
  CRMTokenRecord,
  CRMTokenStore,
  CRMVendorTokenContext,
  PostgresQueryRunner,
  RedisLikeClient,
  SqliteLikeDatabase,
  SqliteLikeStatement,
} from "./stores";
export {
  createInMemoryCRMSyncQueue,
  createPostgresCRMSyncQueue,
  createRedisCRMSyncQueue,
  createSqliteCRMSyncQueue,
} from "./sync";
export type {
  CRMChangeEvent,
  CRMSyncEntityPayload,
  CRMSyncJob,
  CRMSyncJobKind,
  CRMSyncJobStatus,
  CRMSyncQueue,
  CreateInMemoryCRMSyncQueueOptions,
  CreatePostgresCRMSyncQueueOptions,
  CreateRedisCRMSyncQueueOptions,
  CreateSqliteCRMSyncQueueOptions,
  EnqueueCRMSyncJobInput,
  RedisSortedSetClient,
} from "./sync";
export { createCRMRuntime } from "./runtime";
export type {
  CRMConflictResolution,
  CRMConflictResolver,
  CRMRuntime,
  CRMRuntimeChangeListener,
  CRMRuntimeOptions,
} from "./runtime";
export {
  createHubSpotCRMAdapter,
  createSalesforceCRMAdapter,
  HUBSPOT_CONTACT_PROPERTY_NAMES,
  HUBSPOT_DEAL_PROPERTY_NAMES,
  mapHubSpotContactObject,
  mapHubSpotDealObject,
  mapSalesforceAccountRow,
  mapSalesforceContactRow,
  mapSalesforceDealRow,
  mapSalesforceLeadRow,
} from "./adapters";
export type {
  CreateHubSpotCRMAdapterOptions,
  CreateSalesforceCRMAdapterOptions,
  HubSpotBasicApi,
  HubSpotClientLike,
  HubSpotObjectResponse,
  HubSpotPipeline,
  HubSpotPipelineStage,
  HubSpotPipelinesApi,
  HubSpotSearchApi,
  HubSpotSearchResponse,
  SalesforceConnectionLike,
  SalesforceQueryResult,
  SalesforceSaveResult,
} from "./adapters";
export {
  createVoiceCRMBridge,
  createVoiceLeadCapturePathway,
  DEFAULT_VOICE_LEAD_CAPTURE_OPTIONAL_FIELDS,
  DEFAULT_VOICE_LEAD_CAPTURE_REQUIRED_FIELDS,
} from "./voice";
export type {
  CreateVoiceCRMBridgeOptions,
  CreateVoiceLeadCapturePathwayOptions,
  VoiceLeadCaptureField,
} from "./voice";
export {
  createCRMOAuthHandler,
  createCRMWebhookReceiver,
  createPermissiveCRMWebhookVerifier,
  DEFAULT_CRM_CONTEXT_EXTRACTORS,
  getCRMAdapterForUser,
} from "./auth";
export type {
  CRMOAuthContextExtractor,
  CRMOAuthHandler,
  CRMOAuthHandlerOptions,
  CRMOAuthPersistInput,
  CRMOAuthProfileLike,
  CRMOAuthTokenResponseLike,
  CRMOAuthVendorConfig,
  CRMRefreshOAuth,
  CRMRefreshOAuthInput,
  CRMRefreshedToken,
  CRMWebhookHandleResult,
  CRMWebhookInvocation,
  CRMWebhookNormalizer,
  CRMWebhookReceiver,
  CRMWebhookReceiverOptions,
  CRMWebhookSignatureVerifier,
  CRMWebhookVendorConfig,
  GetCRMAdapterForUserOptions,
} from "./auth";
