export type {
  CRMAccount,
  CRMActivity,
  CRMAddress,
  CRMAdapter,
  CRMAdapterCapabilities,
  CRMAdapterFactory,
  CRMAdapterFactoryInput,
  CRMContact,
  CRMCustomField,
  CRMDeal,
  CRMEmail,
  CRMEntityType,
  CRMLead,
  CRMListOptions,
  CRMListResult,
  CRMNote,
  CRMOwner,
  CRMPhone,
  CRMPipeline,
  CRMSocialHandle,
  CRMStage,
  CRMSyncDirection,
  CRMTask,
  CRMVendor,
} from "./types";
export {
  createInMemoryCRMLocalEntityStore,
  createInMemoryCRMTokenStore,
  createPostgresCRMLocalEntityStore,
  createPostgresCRMTokenStore,
  createRedisCRMLocalEntityStore,
  createRedisCRMTokenStore,
  createSqliteCRMLocalEntityStore,
  createSqliteCRMTokenStore,
} from "./stores";
export type {
  CreateInMemoryCRMLocalEntityStoreOptions,
  CreateInMemoryCRMTokenStoreOptions,
  CreatePostgresCRMLocalEntityStoreOptions,
  CreatePostgresCRMTokenStoreOptions,
  CreateRedisCRMLocalEntityStoreOptions,
  CreateRedisCRMTokenStoreOptions,
  CreateSqliteCRMLocalEntityStoreOptions,
  CreateSqliteCRMTokenStoreOptions,
  CRMLocalEntityOrigin,
  CRMLocalEntityRecord,
  CRMLocalEntityStore,
  CRMTokenRecord,
  CRMTokenStore,
  CRMVendorTokenContext,
  PostgresQueryRunner,
  RedisLikeClient,
  SqliteLikeDatabase,
  SqliteLikeStatement,
} from "./stores";
export {
  createCRMReconciler,
  createInMemoryCRMSyncQueue,
  createPostgresCRMSyncQueue,
  createRedisCRMSyncQueue,
  createSqliteCRMSyncQueue,
  lastWriteWinsReconcileResolver,
  remoteWinsReconcileResolver,
} from "./sync";
export type {
  CreateCRMReconcilerOptions,
  CRMChangeEvent,
  CRMReconcileConflictResolution,
  CRMReconcileConflictResolver,
  CRMReconcileConflictResolverInput,
  CRMReconcileResult,
  CRMReconciler,
  CRMReconcilerEvent,
  CRMSyncEntityPayload,
  CRMSyncJob,
  CRMSyncJobKind,
  CRMSyncJobStatus,
  CRMSyncQueue,
  CreateInMemoryCRMSyncQueueOptions,
  CreatePostgresCRMSyncQueueOptions,
  CreateRedisCRMSyncQueueOptions,
  CreateSqliteCRMSyncQueueOptions,
  EnqueueCRMSyncJobInput,
  RedisSortedSetClient,
} from "./sync";
export { createCRMRuntime } from "./runtime";
export type {
  CRMConflictResolution,
  CRMConflictResolver,
  CRMRuntime,
  CRMRuntimeChangeListener,
  CRMRuntimeOptions,
} from "./runtime";
// Re-export the full adapters barrel so EVERY CRM adapter (HubSpot, Salesforce,
// GoHighLevel, Pipedrive, Zoho, Attio, Close, Monday) is available from the package
// root. Adding a new CRM needs no change here — consumers import its factory directly.
export * from "./adapters";
export {
  createVoiceCRMBridge,
  createVoiceLeadCapturePathway,
  DEFAULT_VOICE_LEAD_CAPTURE_OPTIONAL_FIELDS,
  DEFAULT_VOICE_LEAD_CAPTURE_REQUIRED_FIELDS,
} from "./voice";
export type {
  CreateVoiceCRMBridgeOptions,
  CreateVoiceLeadCapturePathwayOptions,
  VoiceLeadCaptureField,
} from "./voice";
export {
  createAttioCRMRefreshOAuth,
  createAttioCRMWebhookConfig,
  createCloseCRMRefreshOAuth,
  createCloseCRMWebhookConfig,
  createCRMOAuthHandler,
  createCRMRefreshOAuth,
  createCRMWebhookReceiver,
  createGoHighLevelCRMRefreshOAuth,
  createGoHighLevelCRMWebhookConfig,
  createHubSpotCRMRefreshOAuth,
  createHubSpotCRMWebhookConfig,
  createMondayCRMRefreshOAuth,
  createMondayCRMWebhookConfig,
  createPermissiveCRMWebhookVerifier,
  createPipedriveCRMRefreshOAuth,
  createPipedriveCRMWebhookConfig,
  createSalesforceCRMRefreshOAuth,
  createSalesforceCRMWebhookConfig,
  createZohoCRMRefreshOAuth,
  createZohoCRMWebhookConfig,
  DEFAULT_CRM_CONTEXT_EXTRACTORS,
  getCRMAdapterForUser,
  normalizeAttioWebhookPayload,
  normalizeCloseWebhookPayload,
  normalizeGoHighLevelWebhookPayload,
  normalizeHubSpotWebhookPayload,
  normalizeMondayWebhookPayload,
  normalizePipedriveWebhookPayload,
  normalizeSalesforceWebhookPayload,
  normalizeZohoWebhookPayload,
  verifyAttioWebhookSignature,
  verifyCloseWebhookSignature,
  verifyGoHighLevelWebhookSignature,
  verifyHubSpotWebhookV3Signature,
  verifyMondayWebhookSignature,
  verifyPipedriveWebhookSignature,
  verifySalesforceWebhookSignature,
  verifyZohoWebhookSignature,
} from "./auth";
export type {
  CreateAttioCRMWebhookConfigOptions,
  CreateCloseCRMWebhookConfigOptions,
  CreateGoHighLevelCRMWebhookConfigOptions,
  CreateHubSpotCRMWebhookConfigOptions,
  CreateMondayCRMWebhookConfigOptions,
  CreatePipedriveCRMWebhookConfigOptions,
  CreateSalesforceCRMWebhookConfigOptions,
  CreateSingleVendorRefreshOAuthOptions,
  CreateZohoCRMWebhookConfigOptions,
  CRMCitraOAuth2ClientLike,
  CRMMultiVendorRefreshOptions,
} from "./auth";
export type {
  CRMOAuthContextExtractor,
  CRMOAuthHandler,
  CRMOAuthHandlerOptions,
  CRMOAuthPersistInput,
  CRMOAuthProfileLike,
  CRMOAuthTokenResponseLike,
  CRMOAuthVendorConfig,
  CRMRefreshOAuth,
  CRMRefreshOAuthInput,
  CRMRefreshedToken,
  CRMWebhookHandleResult,
  CRMWebhookInvocation,
  CRMWebhookNormalizer,
  CRMWebhookReceiver,
  CRMWebhookReceiverOptions,
  CRMWebhookSignatureVerifier,
  CRMWebhookVendorConfig,
  GetCRMAdapterForUserOptions,
} from "./auth";
